# Jenkins Dockerfile
# Docker 공식 이미지 풀: docker pull jenkins/jenkins:lts
# Docker Hub: https://hub.docker.com/r/jenkins/jenkins
# Docker run
# docker run -d -p 8080:8080 -p 50000:50000 --name jenkins -v jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins/jenkins:lts
# ========== 사용법  ========== #

# mkdir -p /home/git/data/jenkins/ssl
# cd /home/git/data/jenkins/ssl

# keytool -genkeypair -alias jenkins -keyalg RSA -keystore jenkins_keystore.p12 -storetype PKCS12 -storepass jenkins1234 -keypass jenkins1234 -validity 3650 -keysize 2048 -dname "CN=192.168.0.12, OU=Dev, O=Company, L=Seoul, ST=your_state, C=KR"

# sudo chown -R 1000:1000 /home/git/data/jenkins/data
# sudo chown -R 1000:1000 /home/git/data/jenkins/ssl

# docker-compose up -d # 백그라운드 실행
# docker start jenkins # 컨테이너 시작
# docker stop jenkins # 컨테이너 중지
# docker-compose down # 컨테이너 삭제

# 도커 초기 비밀번호 확인 docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

# docker logs -f jenkins 로그 확인

# =========================== #

version: '3.6'
services:
  jenkins:
    # build: . # 현재 위치의 Dockerfile로 빌드
    image: jenkins/jenkins:lts # jenkins 공식 이미지 사용
    restart: unless-stopped # 컨테이너가 중지되었을 때 자동 재시작
    hostname: '192.168.0.12'
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/ssl/jenkins_keystore.p12 --httpsKeyStorePassword=jenkins1234
    ports:
    # https
      - "7643:8443"
    # jenkins 마스터 통신 포트 (agent 통신용)
      - "7650:50000"
    volumes:
      - /home/git/data/jenkins/data:/var/jenkins_home # Jenkins 데이터 볼륩 지정
      - /home/git/data/jenkins/ssl:/var/jenkins_home/ssl # SSL 인증서 볼륨 지정
      - /var/run/docker.sock:/var/run/docker.sock # 도커 소캣 바인딩 (Jenkins 내부에서 Docker 명령어 사용)
    # container size (default: 256m)
    shm_size: '8G'